name:    pokedex-pfpa
version: "0.1.0"

dependencies:
- base
- yesod-core

library:
  source-dirs: src

executables:
  pokedex-pfpa:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pokedex-pfpa
